const phoneNumber = [
    "Việt Nam ‏(‎+84)",
    "Ả rập Xê Út ‏(‎+966)",
    "Ác-hen-ti-na ‏(‎+54)",
    "Ác-mê-ni-a ‏(‎+374)",
    "Afghanistan ‏(‎+93)",
    "Ai Cập ‏(‎+20)",
    "Ai-len ‏(‎+353)",
    "Ai-xơ-len ‏(‎+354)",
    "An-ba-ni ‏(‎+355)",
    "An-đô-ra ‏(‎+376)",
    "An-giê-ri ‏(‎+213)",
    "Antigua và Barbuda ‏(‎+1)",
    "Áo ‏(‎+43)",
    "A-ru-ba ‏(‎+297)",
    "Azerbaijan ‏(‎+994)",
    "Ăng-gô-la ‏(‎+244)",
    "Ấn Độ ‏(‎+91)",
    "Ba Lan ‏(‎+48)",
    "Bac-ba-đôt ‏(‎+1)",
    "Bahama ‏(‎+1)",
    "Ba-ranh ‏(‎+973)",
    "Bắc Macedonia ‏(‎+389)",
    "Băng-la-đét ‏(‎+880)",
    "Béc-mu-đa ‏(‎+1)",
    "Bê-la-rút ‏(‎+375)",
    "Bê-li-zơ ‏(‎+501)",
    "Bê-nanh ‏(‎+229)",
    "Bỉ ‏(‎+32)",
    "Bo-ne ‏(‎+599)",
    "Bồ Đào Nha ‏(‎+351)",
    "Bô-li-vi-a ‏(‎+591)",
    "Bốt-xni-a Héc-xê-gô-vi-na ‏(‎+387)",
    "Bốt-xoa-na ‏(‎+267)",
    "Bra-xin ‏(‎+55)",
    "Bru-nây ‏(‎+673)",
    "Bun-ga-ri ‏(‎+359)",
    "Buốc-ki-na Pha-xô ‏(‎+226)",
    "Bu-run-đi ‏(‎+257)",
    "Bu-tan ‏(‎+975)",
    "Cabo Verde ‏(‎+238)",
    "Các tiểu đảo xa Hoa Kỳ ‏(‎+1)",
    "Các tiểu vương quốc Ả rập thống nhất ‏(‎+971)",
    "Ca-mơ-run ‏(‎+237)",
    "Campuchia ‏(‎+855)",
    "Ca-na-đa ‏(‎+1)",
    "Cô-lôm-bi-a ‏(‎+57)",
    "Cô-mô ‏(‎+269)",
    "Cộng hòa Đô-mi-ni-ca ‏(‎+1)",
    "Cộng hòa Trung Phi ‏(‎+236)",
    "Công-gô ‏(‎+242)",
    "Cô-oét ‏(‎+965)",
    "Côte d'Ivoire ‏(‎+225)",
    "Cốt-xta Ri-ca ‏(‎+506)",
    "Croatia ‏(‎+385)",
    "Cu-ba ‏(‎+53)",
    "Cu-ra-xao ‏(‎+599)",
    "Châu Nam cực ‏(‎+672)",
    "CHDC Công-gô ‏(‎+243)",
    "Chile ‏(‎+56)",
    "Chính quyền Quốc gia Pa-lét-xtin ‏(‎+970)",
    "Đài Loan ‏(‎+886)",
    "Đan Mạch ‏(‎+45)",
    "Đảo Axensân ‏(‎+247)",
    "Đảo Bou-vet ‏(‎+47)",
    "Đảo Giáng sinh ‏(‎+61)",
    "Đảo Man ‏(‎+44)",
    "Đặc khu Hành chính Hồng Kông ‏(‎+852)",
    "Đặc khu hành chính Ma-cao ‏(‎+853)",
    "Đô-mi-ni-ca ‏(‎+1)",
    "Đức ‏(‎+49)",
    "En Xan-va-đo ‏(‎+503)",
    "Ét-xtô-ni ‏(‎+372)",
    "Ê-cua-đo ‏(‎+593)",
    "Ê-ri-trê-a ‏(‎+291)",
    "Ê-ti-ô-pi-a ‏(‎+251)",
    "Fiji ‏(‎+679)",
    "Ga-bông ‏(‎+241)",
    "Gambia ‏(‎+220)",
    "Ga-na ‏(‎+233)",
    "Ghi-nê ‏(‎+224)",
    "Ghi-nê Bit-xao ‏(‎+245)",
    "Ghi-nê Xích đạo ‏(‎+240)",
    "Goa-đơ-lup ‏(‎+590)",
    "Greenland ‏(‎+299)",
    "Grê-na-đa ‏(‎+1)",
    "Gru-di-a ‏(‎+995)",
    "Guam ‏(‎+1)",
    "Guatemala ‏(‎+502)",
    "Guernsey ‏(‎+44)",
    "Guy-an thuộc Pháp ‏(‎+594)",
    "Guyana ‏(‎+592)",
    "Gi-bran-ta ‏(‎+350)",
    "Gioóc-đan ‏(‎+962)",
    "Hà Lan ‏(‎+31)",
    "Hai-ti ‏(‎+509)",
    "Hàn Quốc ‏(‎+82)",
    "Hoa Kỳ ‏(‎+1)",
    "Hôn-đu-ras ‏(‎+504)",
    "Hung-ga-ri ‏(‎+36)",
    "Hy Lạp ‏(‎+30)",
    "Ian May-en ‏(‎+47)",
    "In-đô-nê-xi-a ‏(‎+62)",
    "I-ran ‏(‎+98)",
    "I-rắc ‏(‎+964)",
    "I-ta-li-a ‏(‎+39)",
    "I-xra-en ‏(‎+972)",
    "Ja-mai-ca ‏(‎+1)",
    "Ji-bu-ti ‏(‎+253)",
    "Jơ-xy ‏(‎+44)",
    "Ka-zắc-xtan ‏(‎+7)",
    "Kê-ny-a ‏(‎+254)",
    "Ki-ri-ba-ti ‏(‎+686)",
    "Ki-rơ-ghi-xtan ‏(‎+996)",
    "Kosovo ‏(‎+383)",
    "Lãnh thổ Ấn độ dương thuộc Anh ‏(‎+44)",
    "Lào ‏(‎+856)",
    "Lat-vi-a ‏(‎+371)",
    "Lesotho ‏(‎+266)",
    "Li-băng ‏(‎+961)",
    "Li-bê-ri-a ‏(‎+231)",
    "Li-bi ‏(‎+218)",
    "Lích-ten-xten ‏(‎+423)",
    "Lít-va ‏(‎+370)",
    "Lúc-xem-bua ‏(‎+352)",
    "Mác-ti-ních ‏(‎+596)",
    "Ma-đa-gát-xca ‏(‎+261)",
    "Ma-lai-xi-a ‏(‎+60)",
    "Ma-la-uy ‏(‎+265)",
    "Ma-li ‏(‎+223)",
    "Man-đi-vơ ‏(‎+960)",
    "Man-ta ‏(‎+356)",
    "Ma-rốc ‏(‎+212)",
    "Mau-ri-ti-utx ‏(‎+230)",
    "May-ôt ‏(‎+262)",
    "Mê-hi-cô ‏(‎+52)",
    "Mi-crô-nê-si-a ‏(‎+691)",
    "Mô-na-cô ‏(‎+377)",
    "Môn-đô-va ‏(‎+373)",
    "Môn-tê-nê-grô ‏(‎+382)",
    "Môn-xê-rát ‏(‎+1)",
    "Mông Cổ ‏(‎+976)",
    "Mô-ri-ta-ni ‏(‎+222)",
    "Mô-zăm-bích ‏(‎+258)",
    "My-an-ma ‏(‎+95)",
    "Nam Phi ‏(‎+27)",
    "Nam Sudan ‏(‎+211)",
    "Na-mi-bi-a ‏(‎+264)",
    "Nauru ‏(‎+674)",
    "Na-uy ‏(‎+47)",
    "Nê-pan ‏(‎+977)",
    "Nicaragua ‏(‎+505)",
    "Ni-giê ‏(‎+227)",
    "Ni-giê-ri-a ‏(‎+234)",
    "Niu Ca-lê-đô-ni ‏(‎+687)",
    "Niu Di-lân ‏(‎+64)",
    "Niu-ê ‏(‎+683)",
    "Nga ‏(‎+7)",
    "Nhật Bản ‏(‎+81)",
    "Ô-man ‏(‎+968)",
    "Pakistan ‏(‎+92)",
    "Palau ‏(‎+680)",
    "Pa-na-ma ‏(‎+507)",
    "Pa-pua Niu Ghi-nê ‏(‎+675)",
    "Pa-ra-goay ‏(‎+595)",
    "Pê-ru ‏(‎+51)",
    "Polynesia thuộc Pháp ‏(‎+689)",
    "Pháp ‏(‎+33)",
    "Phần Lan ‏(‎+358)",
    "Phi-líp-pin ‏(‎+63)",
    "Qua-ta ‏(‎+974)",
    "Quần đảo Bắc Ma-ri-a-na ‏(‎+1)",
    "Quần đảo Cay-man ‏(‎+1)",
    "Quần đảo Cocos (Keeling) ‏(‎+61)",
    "Quần đảo Cúc ‏(‎+682)",
    "Quần đảo Falkland ‏(‎+500)",
    "Quần đảo Fa-rôi ‏(‎+298)",
    "Quần đảo Mác-san ‏(‎+692)",
    "Quần đảo Tơc và Kây-kôt ‏(‎+1)",
    "Quần đảo Virgin thuộc Anh ‏(‎+1)",
    "Quần đảo Virgin thuộc Hoa Kỳ ‏(‎+1)",
    "Quần đảo Xô-lô-môn ‏(‎+677)",
    "Quốc đảo Hà Lan (Trước đây) ‏(‎+599)",
    "Réunion ‏(‎+262)",
    "Ru-ma-ni ‏(‎+40)",
    "Ru-oan-đa ‏(‎+250)",
    "Sa-ba ‏(‎+599)",
    "Saint Kitts và Nevis ‏(‎+1)",
    "Saint Lucia ‏(‎+1)",
    "Saint Pierre và Miquelon ‏(‎+508)",
    "Saint Vincent và Grenadines ‏(‎+1)",
    "Sat ‏(‎+235)",
    "Séc ‏(‎+420)",
    "Séc-bi ‏(‎+381)",
    "Sint Eustatius ‏(‎+599)",
    "Síp ‏(‎+357)",
    "Slô-va-ki-a ‏(‎+421)",
    "Slô-ve-ni-a ‏(‎+386)",
    "St Helena, Ascension và Tristan da Cunha ‏(‎+290)",
    "Svalbard ‏(‎+47)",
    "Tajikistan ‏(‎+992)",
    "Tan-za-ni-a ‏(‎+255)",
    "Tây Ban Nha ‏(‎+34)",
    "Timo Lextơ ‏(‎+670)",
    "Tô-gô ‏(‎+228)",
    "Tô-kê-lau ‏(‎+690)",
    "Tông-ga ‏(‎+676)",
    "Tơ-ri-ni-đát và Tô-ba-gô ‏(‎+1)",
    "Tơrixtan đa Cunha ‏(‎+290)",
    "Turkmenistan ‏(‎+993)",
    "Tu-va-lu ‏(‎+688)",
    "Tuy-ni-di ‏(‎+216)",
    "Thái Lan ‏(‎+66)",
    "Thành Vatican ‏(‎+379)",
    "Thổ Nhĩ Kỳ ‏(‎+90)",
    "Thụy Điển ‏(‎+46)",
    "Thụy Sĩ ‏(‎+41)",
    "Trung Quốc ‏(‎+86)",
    "Úc ‏(‎+61)",
    "U-gan-đa ‏(‎+256)",
    "Ukraina ‏(‎+380)",
    "U-ru-goay ‏(‎+598)",
    "Uzbekistan ‏(‎+998)",
    "Vanuatu ‏(‎+678)",
    "Vê-nê-zuê-la ‏(‎+58)",
    "Vương quốc Anh ‏(‎+44)",
    "Wallis và Futuna ‏(‎+681)",
    "Xa-moa ‏(‎+685)",
    "Xan Ma-ri-nô ‏(‎+378)",
    "Xao Tô-mê và Prin-xi-pê ‏(‎+239)",
    "Xây-sen ‏(‎+248)",
    "Xê-nê-gan ‏(‎+221)",
    "Xi-ê-ra Lê-ôn ‏(‎+232)",
    "Xinh-ga-po ‏(‎+65)",
    "Xoa-di-len ‏(‎+268)",
    "Xô-ma-li ‏(‎+252)",
    "Xri Lan-ka ‏(‎+94)",
    "Xu-đăng ‏(‎+249)",
    "Xu-ri-nam ‏(‎+597)",
    "Xy-ri ‏(‎+963)",
    "Y-ê-men ‏(‎+967)",
    "Zăm-bi-a ‏(‎+260)",
    "Zim-ba-buê ‏(‎+263)"
]
export default phoneNumber