const image = {
    img1: require('./img1.jpg'),
    img2: require('./img2.jpg'),
    img3: require('./img3.jpg'),
    img4: require('./img4.jpg'),
    img5: require('./img5.jpg'),
    img6: require('./img6.jpg'),
    img7: require('./img7.jpg'),
    img8: require('./img8.jpg'),
    img9: require('./img9.jpg'),
    img10: require('./img10.jpg'),
    img11: require('./img11.jpg'),
    img12: require('./img12.jpg'),
    zalo1: require('./img13.jpg'),
    zalo2: require('./img14.jpg'),
    zalo3: require('./img15.jpg'),
    zalo4: require('./img16.jpg'),
    zalo5: require('./img17.jpg'),
    zalo6: require('./img18.jpg'),
}
export default image